### PR TITLE
Idea sheet – MERGE WITH WINNIES APPROVAL

### PR DESCRIPTION
**Pull request by mattfxyz**
This adds everything requested from todays Slack chat

* Link to become a mentor" – waiting on winnies approval. 

The mentor submit link is  under "sponsorship & mentors". 

* Link to "Submit an idea"

### CODE REVIEW

**Comment by mattfxyz** [comment]
WINNIE APPROVES @KevinPayravi

**Comment by KevinPayravi** [comment]
Think we should add a button to the mentor application at the top? It's a bit easier to find that way.

**Comment by mattfxyz** [comment]
I agree, but I wasn’t sure where to put it. Four buttons seems like too much.

**Comment by KevinPayravi** [comment]
True...to clarify, is the purpose of the "submit an idea" button to get ideas for hacks from people?

**Comment by mattfxyz** [comment]
Yeah. Per @arnab and Meris

**Comment by KevinPayravi** [comment]
Quick concept I threw up in MS Paint - thoughts?

image

**Comment by mattfxyz** [comment]
I like this. Lets make it a ReAlItY

**Comment by arnabdotorg** [comment]
@KevinPayravi is this broken? Link should go to go.osu.edu/hackideas2015

**Comment by KevinPayravi** [comment]
@arnabdotorg Fixed, thanks! Should be fixed on next site refresh. @mattfxyz

**Pull request merged**
