### PR TITLE
Adding showcase button

### PR DESCRIPTION
**Pull request by KevinPayravi**
Would like it to say "Showcase Tickets", but then the button becomes two lines. Should probably explore how to better organize these.

### CODE REVIEW

**Comment by mattfxyz** [comment]
I think we reached the point of too many links

**Comment by KevinPayravi** [comment]
@mattfxyz Agreed

**Comment by egladman** [comment]
@KevinPayravi 

```
white-space: nowrap;
```

should prevent buttons from taking up two lines

**Comment by mattfxyz** [comment]
Kevin added a `<br/>` 

It's not the amount of lines, it's the amount of buttons.

**Pull request merged**
